---
version: "2.1"
services:
  adguardhome-sync:
    image: lscr.io/linuxserver/adguardhome-sync:latest
    container_name: adguardhome-sync
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config/adguardhome-sync.yaml:/config/adguardhome-sync.yaml
    ports:
      - 9180:8080
    network_mode: bridge
    restart: unless-stopped