---
version: "2.1"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    environment:
      - TZ=US/New_York
    volumes:
      - ./config:/opt/adguardhome/conf
      - ./work:/opt/adguardhome/work
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 9080:80/tcp
      - 3000:3000/tcp
      - 9443:443/tcp
      - 9443:443/udp
    networks:
      default:
        ipv4_address: 172.28.0.3
    restart: unless-stopped
  unbound:
     image: klutchell/unbound
     networks:
       default:
         ipv4_address: 172.28.0.2
     restart: unless-stopped
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
          gateway: 172.28.0.1