version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /opt/appdata/plex/config:/config
      - /mnt/plexmedia/tv:/tv
      - /mnt/plexmedia/movies:/movies
    ports:
      - 32400:32400
    devices:
      - /dev/dri:/dev/dri #intel igpu pass-through
    restart: unless-stopped